Replace block tunes HTML with config
editor-js/quote pull request #48
Opened 2022-11-04 17:22 UTC by TatianaFomina

Update `renderSettings()` to return array of popover items instead of HTML with custom buttons.
Uses new configuration format introduced in https://github.com/codex-team/editor.js/pull/2091

<img width="205" alt="image" src="https://user-images.githubusercontent.com/31101125/200037433-181b6743-e8ff-4a00-b9d4-bce809007a79.png">

2022-11-04 19:59 UTC, neSpecc requested changes

2022-11-04 19:59 UTC, neSpecc commented on src/index.js
> +      label: `${capitalize(item.name)} alignment`,
add [i18n api](https://editorjs.io/i18n-api) wrapper please

2022-11-05 15:55 UTC, neSpecc approved these changes, later dismissed
increment version pls

2022-11-29 19:05 UTC, neSpecc approved these changes

2022-11-29 19:06 UTC, ilyamore88 approved these changes

2022-11-29 19:08 UTC, merged